#!/bin/bash -l

#SBATCH --ntasks=$swift_num_nodes
#SBATCH -J $sim_name
#SBATCH -o ./out_files/%x.%J.swift.out
#SBATCH -e ./out_files/%x.%J.swift.err
#SBATCH -p cosma7
#SBATCH -A dp004
#SBATCH --exclusive
#SBATCH --cpus-per-task=28
#SBATCH --time=$swift_runtime_hours:00:00
#SBATCH --no-requeue

module purge
module load intel_comp/2020-update2
module load intel_mpi/2020-update2
module load ucx/1.8.1
module load parmetis/4.0.3-64bit
module load parallel_hdf5/1.10.6
module load fftw/3.3.8cosma7
module load gsl/2.5

mpirun -np $$SLURM_NTASKS $swift_exec -v 1 --pin --cosmology --self-gravity --threads=$$SLURM_CPUS_PER_TASK params.yml --fof params.yml

echo "Job done, info follows..."
sacct -j $$SLURM_JOBID --format=JobID,JobName,Partition,AveRSS,MaxRSS,AveVMSize,MaxVMSize,Elapsed,ExitCode
