#!/bin/bash -l

#SBATCH --ntasks=$icgen_n_cores
#SBATCH --job-name=ICG-$sim_name
#SBATCH --output=log_%j.txt
#SBATCH --partition=$slurm_partition
#SBATCH --account=$slurm_account
#SBATCH --exclusive
#SBATCH --time=$icgen_runtime_hours:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=$slurm_email

$icgen_module_setup

mpirun -env I_MPI_PIN=1 -env I_MPI_PIN_PROCESSOR_LIST=allcores \
 -np $$SLURM_NTASKS $icgen_exec ./params.inp

echo "Job done, info follows..."
sacct -j $$SLURM_JOBID --format=JobID,JobName,Partition,AveRSS,MaxRSS,AveVMSize,MaxVMSize,Elapsed,ExitCode
exit

